package com.insacosa.entitats;

// Generated 12/12/2011 11:55:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaractinmoblesId generated by hbm2java
 */
@Embeddable
public class CaractinmoblesId implements java.io.Serializable {

	private Long idcaract;
	private int idinmoble;

	public CaractinmoblesId() {
	}

	public CaractinmoblesId(Long idcaract, int idinmoble) {
		this.idcaract = idcaract;
		this.idinmoble = idinmoble;
	}

	public Long getIdcaract() {
		return this.idcaract;
	}

	public void setIdcaract(Long idcaract) {
		this.idcaract = idcaract;
	}

	public int getIdinmoble() {
		return this.idinmoble;
	}

	public void setIdinmoble(int idinmoble) {
		this.idinmoble = idinmoble;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaractinmoblesId))
			return false;
		CaractinmoblesId castOther = (CaractinmoblesId) other;

		return (this.getIdcaract() == castOther.getIdcaract())
				&& (this.getIdinmoble() == castOther.getIdinmoble());
	}

}
