package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComptadorId generated by hbm2java
 */
@Embeddable
public class ComptadorId implements java.io.Serializable {

	private String taulaid;
	private int comptador;

	public ComptadorId() {
	}

	public ComptadorId(int comptador) {
		this.comptador = comptador;
	}

	public ComptadorId(String taulaid, int comptador) {
		this.taulaid = taulaid;
		this.comptador = comptador;
	}

	@Column(name = "TAULAID", length = 50)
	public String getTaulaid() {
		return this.taulaid;
	}

	public void setTaulaid(String taulaid) {
		this.taulaid = taulaid;
	}

	@Column(name = "COMPTADOR", nullable = false)
	public int getComptador() {
		return this.comptador;
	}

	public void setComptador(int comptador) {
		this.comptador = comptador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComptadorId))
			return false;
		ComptadorId castOther = (ComptadorId) other;

		return ((this.getTaulaid() == castOther.getTaulaid()) || (this
				.getTaulaid() != null && castOther.getTaulaid() != null && this
				.getTaulaid().equals(castOther.getTaulaid())))
				&& (this.getComptador() == castOther.getComptador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTaulaid() == null ? 0 : this.getTaulaid().hashCode());
		result = 37 * result + this.getComptador();
		return result;
	}

}
