package com.degloba.HBM;

// Generated 14/11/2011 10:33:52 by Hibernate Tools 3.4.0.CR1

import com.degloba.interfaces.Objecte;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Provincies generated by hbm2java
 */
@Entity
@Table(name = "PROVINCIES", schema = "dbo", catalog = "INSACO")
public class Provincies extends Objecte implements java.io.Serializable {

	private int id;
	private Date tmstamp;
	private String code;
	private String name;
	private Set<Inmobles> inmobleses = new HashSet<Inmobles>(0);

	public Provincies() {
	}

	public Provincies(int id, Date tmstamp, String code, String name) {
		this.id = id;
		this.tmstamp = tmstamp;
		this.code = code;
		this.name = name;
	}

	public Provincies(int id, Date tmstamp, String code, String name,
			Set<Inmobles> inmobleses) {
		this.id = id;
		this.tmstamp = tmstamp;
		this.code = code;
		this.name = name;
		this.inmobleses = inmobleses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tmstamp", nullable = false, length = 23)
	public Date getTmstamp() {
		return this.tmstamp;
	}

	public void setTmstamp(Date tmstamp) {
		this.tmstamp = tmstamp;
	}

	@Column(name = "code", nullable = false, length = 16)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincies")
	public Set<Inmobles> getInmobleses() {
		return this.inmobleses;
	}

	public void setInmobleses(Set<Inmobles> inmobleses) {
		this.inmobleses = inmobleses;
	}

}
