package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * Solicituds generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUDS", schema = "dbo", catalog = "INSACO")
@TableGenerator(name="TABLE_GEN", schema = "dbo", catalog = "INSACO", table="COMPTADOR", pkColumnName="TAULAID",
	        valueColumnName="COMPTADOR", pkColumnValue="SOLICITUDS", allocationSize=1)
public class Solicituds implements java.io.Serializable {

	private int id;
	private Inmobles inmobles;
	private Usuaris usuaris;

	public Solicituds() {
	}

	public Solicituds(int id) {
		this.id = id;
	}

	public Solicituds(int id, Inmobles inmobles, Usuaris usuaris) {
		this.id = id;
		this.inmobles = inmobles;
		this.usuaris = usuaris;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.TABLE, generator="TABLE_GEN")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMOBLE")
	public Inmobles getInmobles() {
		return this.inmobles;
	}

	public void setInmobles(Inmobles inmobles) {
		this.inmobles = inmobles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPRADOR")
	public Usuaris getUsuaris() {
		return this.usuaris;
	}

	public void setUsuaris(Usuaris usuaris) {
		this.usuaris = usuaris;
	}

}
