package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.appengine.api.datastore.Key;

/**
 * Ttpbasic generated by hbm2java
 */
@Entity
@Table(name = "TTPBASIC", schema = "dbo", catalog = "INSACO")
public class Ttpbasic implements java.io.Serializable {

	private String ktpbasic;
	private String bdtype;
	private Set<Caracteristiques> caracteristiqueses = new HashSet<Caracteristiques>(
			0);
	
    @Id
    @GeneratedValue
    private Key key;

	public Ttpbasic() {
	}

	public Ttpbasic(String ktpbasic) {
		this.ktpbasic = ktpbasic;
	}

	public Ttpbasic(String ktpbasic, String bdtype,
			Set<Caracteristiques> caracteristiqueses) {
		this.ktpbasic = ktpbasic;
		this.bdtype = bdtype;
		this.caracteristiqueses = caracteristiqueses;
	}


    // Accessors for the fields. JPA doesn't use these, but your application does.    
    public Key getKey() {        
    	return key;    
    }
    
    public void setKey(Key key) {        
    	this.key = key;    
    }
    
	@Column(name = "BDTYPE", length = 20)
	public String getBdtype() {
		return this.bdtype;
	}

	public void setBdtype(String bdtype) {
		this.bdtype = bdtype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttpbasic")
	public Set<Caracteristiques> getCaracteristiqueses() {
		return this.caracteristiqueses;
	}

	public void setCaracteristiqueses(Set<Caracteristiques> caracteristiqueses) {
		this.caracteristiqueses = caracteristiqueses;
	}

}
