package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ttpcontrol generated by hbm2java
 */
@Entity
@Table(name = "TTPCONTROL", schema = "dbo", catalog = "INSACO")
public class Ttpcontrol implements java.io.Serializable {

	private String ktpcontrol;
	private Set<Caracteristiques> caracteristiqueses = new HashSet<Caracteristiques>(
			0);

	public Ttpcontrol() {
	}

	public Ttpcontrol(String ktpcontrol) {
		this.ktpcontrol = ktpcontrol;
	}

	public Ttpcontrol(String ktpcontrol,
			Set<Caracteristiques> caracteristiqueses) {
		this.ktpcontrol = ktpcontrol;
		this.caracteristiqueses = caracteristiqueses;
	}

	@Id
	@Column(name = "KTPCONTROL", unique = true, nullable = false, length = 4)
	public String getKtpcontrol() {
		return this.ktpcontrol;
	}

	public void setKtpcontrol(String ktpcontrol) {
		this.ktpcontrol = ktpcontrol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttpcontrol")
	public Set<Caracteristiques> getCaracteristiqueses() {
		return this.caracteristiqueses;
	}

	public void setCaracteristiqueses(Set<Caracteristiques> caracteristiqueses) {
		this.caracteristiqueses = caracteristiqueses;
	}

}
