package com.degloba.HBM;

// Generated 12/12/2011 11:55:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.google.appengine.api.datastore.Key;

/**
 * Caractinmobles generated by hbm2java
 */
@Entity
@Table(name = "CARACTINMOBLES", schema = "dbo", catalog = "INSACO")
public class Caractinmobles implements java.io.Serializable {

    @Id
    @GeneratedValue
    private Key key;
	
	private CaractinmoblesId id;

	public Caractinmobles() {
	}

	public Caractinmobles(CaractinmoblesId id) {
		this.id = id;
	}

	public CaractinmoblesId getId() {
		return this.id;
	}

    // Accessors for the fields. JPA doesn't use these, but your application does.    
    public Key getKey() {        
    	return key;    
    }
    
    public void setKey(Key key) {        
    	this.key = key;    
    }

}
