package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Comptador generated by hbm2java
 */
@Entity
@Table(name = "COMPTADOR", schema = "dbo", catalog = "INSACO")
public class Comptador implements java.io.Serializable {

	private ComptadorId id;

	public Comptador() {
	}

	public Comptador(ComptadorId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "taulaid", column = @Column(name = "TAULAID", length = 50)),
			@AttributeOverride(name = "comptador", column = @Column(name = "COMPTADOR", nullable = false)) })
	public ComptadorId getId() {
		return this.id;
	}

	public void setId(ComptadorId id) {
		this.id = id;
	}

}
