package com.degloba.HBM;

// Generated 13/12/2011 09:53:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PersonesAdreces generated by hbm2java
 */
@Entity
@Table(name = "personesAdreces", schema = "dbo", catalog = "INSACO")
public class PersonesAdreces implements java.io.Serializable {

	private int idAdrecaPa;
	private Persona persona;
	private Adreces adreces;

	public PersonesAdreces() {
	}

	public PersonesAdreces(Adreces adreces) {
		this.adreces = adreces;
	}

	public PersonesAdreces(Persona persona, Adreces adreces) {
		this.persona = persona;
		this.adreces = adreces;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "adreces"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_adreca_pa", unique = true, nullable = false)
	public int getIdAdrecaPa() {
		return this.idAdrecaPa;
	}

	public void setIdAdrecaPa(int idAdrecaPa) {
		this.idAdrecaPa = idAdrecaPa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_pa")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Adreces getAdreces() {
		return this.adreces;
	}

	public void setAdreces(Adreces adreces) {
		this.adreces = adreces;
	}

}
