package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.google.appengine.api.datastore.Key;

/**
 * Solicituds generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUDS", schema = "dbo", catalog = "INSACO")
@TableGenerator(name="TABLE_GEN", schema = "dbo", catalog = "INSACO", table="COMPTADOR", pkColumnName="TAULAID",
	        valueColumnName="COMPTADOR", pkColumnValue="SOLICITUDS", allocationSize=1)
public class Solicituds implements java.io.Serializable {


	private Inmobles inmobles;
	private Usuaris usuaris;
	
    @Id
    @GeneratedValue
    private Key key;

	public Solicituds() {
	}

	public Solicituds(Key id) {
		this.key = id;
	}

	public Solicituds(Key id, Inmobles inmobles, Usuaris usuaris) {
		this.key = id;
		this.inmobles = inmobles;
		this.usuaris = usuaris;
	}

    // Accessors for the fields. JPA doesn't use these, but your application does.    
    public Key getKey() {        
    	return key;    
    }
    
    public void setKey(Key key) {        
    	this.key = key;    
    }


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMOBLE")
	public Inmobles getInmobles() {
		return this.inmobles;
	}

	public void setInmobles(Inmobles inmobles) {
		this.inmobles = inmobles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPRADOR")
	public Usuaris getUsuaris() {
		return this.usuaris;
	}

	public void setUsuaris(Usuaris usuaris) {
		this.usuaris = usuaris;
	}

}
