package com.degloba.HBM;

// Generated 16/11/2011 13:01:35 by Hibernate Tools 3.4.0.CR1

import com.degloba.interfaces.Objecte;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipus generated by hbm2java
 */
@Entity
@Table(name = "TIPUS", schema = "dbo", catalog = "INSACO")
public class Tipus extends Objecte implements java.io.Serializable {

	private int id;
	private String nom;
	private Set<Inmobles> inmobleses = new HashSet<Inmobles>(0);
	private Set<Caracteristiques> caracteristiqueses = new HashSet<Caracteristiques>(
			0);

	public Tipus() {
	}

	public Tipus(int id) {
		this.id = id;
	}

	public Tipus(int id, String nom, Set<Inmobles> inmobleses,
			Set<Caracteristiques> caracteristiqueses) {
		this.id = id;
		this.nom = nom;
		this.inmobleses = inmobleses;
		this.caracteristiqueses = caracteristiqueses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NOM", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipus")
	public Set<Inmobles> getInmobleses() {
		return this.inmobleses;
	}

	public void setInmobleses(Set<Inmobles> inmobleses) {
		this.inmobleses = inmobleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipus")
	public Set<Caracteristiques> getCaracteristiqueses() {
		return this.caracteristiqueses;
	}

	public void setCaracteristiqueses(Set<Caracteristiques> caracteristiqueses) {
		this.caracteristiqueses = caracteristiqueses;
	}

}
