package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ValuesCaracteristiques generated by hbm2java
 */
@Entity
@Table(name = "VALUES_CARACTERISTIQUES", schema = "dbo", catalog = "INSACO")
public class ValuesCaracteristiques implements java.io.Serializable {

	private ValuesCaracteristiquesId id;
	private Caracteristiques caracteristiques;
	private Inmobles inmobles;
	private String value;

	public ValuesCaracteristiques() {
	}

	public ValuesCaracteristiques(ValuesCaracteristiquesId id,
			Caracteristiques caracteristiques, Inmobles inmobles) {
		this.id = id;
		this.caracteristiques = caracteristiques;
		this.inmobles = inmobles;
	}

	public ValuesCaracteristiques(ValuesCaracteristiquesId id,
			Caracteristiques caracteristiques, Inmobles inmobles, String value) {
		this.id = id;
		this.caracteristiques = caracteristiques;
		this.inmobles = inmobles;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idinmoble", column = @Column(name = "IDINMOBLE", nullable = false)),
			@AttributeOverride(name = "idcaracteristica", column = @Column(name = "IDCARACTERISTICA", nullable = false, precision = 18, scale = 0)) })
	public ValuesCaracteristiquesId getId() {
		return this.id;
	}

	public void setId(ValuesCaracteristiquesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCARACTERISTICA", nullable = false, insertable = false, updatable = false)
	public Caracteristiques getCaracteristiques() {
		return this.caracteristiques;
	}

	public void setCaracteristiques(Caracteristiques caracteristiques) {
		this.caracteristiques = caracteristiques;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMOBLE", nullable = false, insertable = false, updatable = false)
	public Inmobles getInmobles() {
		return this.inmobles;
	}

	public void setInmobles(Inmobles inmobles) {
		this.inmobles = inmobles;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
