package com.degloba.HBM;

// Generated 27/01/2012 12:51:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValuesCaracteristiquesId generated by hbm2java
 */
@Embeddable
public class ValuesCaracteristiquesId implements java.io.Serializable {

	private int idinmoble;
	private long idcaracteristica;

	public ValuesCaracteristiquesId() {
	}

	public ValuesCaracteristiquesId(int idinmoble, long idcaracteristica) {
		this.idinmoble = idinmoble;
		this.idcaracteristica = idcaracteristica;
	}

	@Column(name = "IDINMOBLE", nullable = false)
	public int getIdinmoble() {
		return this.idinmoble;
	}

	public void setIdinmoble(int idinmoble) {
		this.idinmoble = idinmoble;
	}

	@Column(name = "IDCARACTERISTICA", nullable = false, precision = 18, scale = 0)
	public long getIdcaracteristica() {
		return this.idcaracteristica;
	}

	public void setIdcaracteristica(long idcaracteristica) {
		this.idcaracteristica = idcaracteristica;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValuesCaracteristiquesId))
			return false;
		ValuesCaracteristiquesId castOther = (ValuesCaracteristiquesId) other;

		return (this.getIdinmoble() == castOther.getIdinmoble())
				&& (this.getIdcaracteristica() == castOther
						.getIdcaracteristica());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdinmoble();
		result = 37 * result + (int) this.getIdcaracteristica();
		return result;
	}

}
